export const routes = {
  home: "/",
  publicReports: "/public-reports",
  about: "/about",
  security: "/security",
  inviteCode: "/auth/invite-code",
  login: "/auth/login",
  /** Force password change after sign-in (users created by admin) */
  changePasswordRequired: "/auth/change-password",
  passkeyRegister: "/auth/passkey/register",
  passkeyVerify: "/auth/passkey/verify",
  mainMenu: "/panel",
  settings: "/panel/settings",
  myTokens: "/panel/my-tokens",
  reportCategory: "/panel/report/category",
  reportBasicInfo: "/panel/report/basic-info",
  reportOrganization: "/panel/report/organization",
  reportPerson: "/panel/report/person",
  reportLocation: "/panel/report/location",
  reportOccurrence: "/panel/report/occurrence",
  reportEvidence: "/panel/report/evidence",
  reportContact: "/panel/report/contact",
  reportConfirmation: "/panel/report/confirmation",
  reportSuccess: "/panel/report/success",
  reportFamous: "/panel/report/famous",
  reportManual: "/panel/report/manual",
  myRequests: "/panel/my-requests",
  /** Report search — validators only */
  reportSearch: "/panel/report-search",
  requestDetail: (id: string) => `/panel/request/${id}`,
  approvalList: "/panel/approval-list",
  inviteUser: "/panel/invite-user",
  register: "/auth/register",
} as const;
