{{- if .Values.tor.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "daadnegar-chart.fullname" . }}-tor-config
  labels:
    {{- include "daadnegar-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: tor
data:
  torrc: |
    DataDirectory /var/lib/tor
    HiddenServiceDir /tor-data/hidden_service/
    HiddenServicePort 80 {{ include "daadnegar-chart.fullname" . }}:{{ .Values.service.port }}
    SocksPort 0
    Log notice stdout
{{- end }}
